# Site settings
title: "goto picular;"
email: atopicular@gmail.com
description: "Programming side blog of topicular."
baseurl: ""
url: "http://metnias.github.io"
title_description: "Programming side of blog of topicular.<br>Mod Manager UI Lead Dev - Rain World: Downpour<br>Korean Translation - Bug Fables: The Everlasting Sapling"
title_image: "favicons/android-chrome-512x512.png"
# google_analytics: "UA-########-#"
# disqus_account: aTopicular
# github_repository: 
# addthis_id: ra-################
post_limit: 5

# Social usernames/URLs
# twitter_username: 
github_username: metnias
# instagram_username: 
# reddit_username: 
# linkedin_link: 
# google_plus_link: 
# stackoverflow_link: 
# xing_link:
# facebook_link:

# Footer
footer_left: "<a href=\"https://topicular.blogspot.com/\">Personal Blog</a>(Korean)"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/metnias?tab=repositories\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
